# -*- encoding: utf-8 -*-

"""
Django settings for ERP_DXM project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# bibliotecas de configuracao
try:
    from .config import config, nomeConfig
except:
    import os

    PROJECT_ROOT_PATH = os.path.dirname(os.path.abspath(__file__))
    config = {}

    # Local com sqlite
    config.update(
        {'testeSqlite':
            {
                'server': False,
                'debug': True,
                'database_engine': 'django.db.backends.sqlite3',
                'database_name': os.path.join(BASE_DIR, 'erp_dxm.sqlite3'),
                'database_user': '',
                'database_password': '',
                'database_host': '',
                'database_port': '',
                'media_url': '/media/',
                'media_root': os.path.dirname(os.path.abspath(__file__)),
                'admin_media_prefix': '/admin/',
                'secret_key': 'yvx+n%mas8)hk79-$p$fteqe_0m2$58-y7+jjwow*h%bte(s)$',
                'static_url': '/static/',
                'static_root': os.path.join(PROJECT_ROOT_PATH, 'static'),
                'email_use_tls': False,
                'email_host': '',
                'email_host_user': '',
                'email_host_password': '',
                'email_port': 0,
            }
        }
    )
    nomeConfig = 'testeSqlite'

#Define qual ambiente irá usar
config = config[nomeConfig]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd4s718p(#5&5w)5oxys!lmn@y$fwx-%zyyv*8y7hmrpd4mz8#l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'material',
    'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Financeiro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ERP_DXM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ERP_DXM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config['database_engine'],
        'NAME': config['database_name'],
        'USER': config['database_user'],
        'PASSWORD': config['database_password'],
        'HOST': config['database_host'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# number formats
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#caminho do projeto
PROJECT_ROOT_PATH = os.path.dirname(os.path.abspath(__file__))

STATICFILES_DIRS = (('site', os.path.join(PROJECT_ROOT_PATH, 'sitestatic')),)
STATIC_URL = config['static_url']
STATIC_ROOT = config['static_root']

# Grapelli
GRAPPELLI_ADMIN_TITLE = 'DXM ERP'
